name: Test actions

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello Inline World"
  say-hello-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello Python World")
        shell: python
  say-hello-actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "testtesttest"
      
